# Generated by Django 3.1.1 on 2020-09-12 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locality_address', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('fire', 'Incêndio'), ('drowning', 'Afogamento'), ('accident', 'Acidente Trânsito')], max_length=32)),
                ('event_time', models.DateTimeField(blank=True, null=True)),
                ('event_status', models.CharField(choices=[('waiting', 'waiting avaliable team'), ('send', 'team was sent'), ('done', 'event already solved')], default='waiting', max_length=32)),
                ('team_confirmation', models.BooleanField(default=False)),
                ('team_time', models.DateTimeField(blank=True, null=True)),
                ('team', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
